[phases.setup]
nixPkgs = [
  "nodejs_18",
  "yarn",
  "python3",
  "gcc",
  "gnumake",
  "chromium",
  "nss",
  "freetype",
  "harfbuzz",
  "fontconfig",
  "liberation_ttf"
]

[phases.install]
cmds = [
  "npm ci --only=production",
  "npx puppeteer browsers install chrome --path /tmp/chrome || echo 'Chrome download failed, using system chromium'"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "false"
# No establecer PUPPETEER_EXECUTABLE_PATH aquí, dejar que el código lo detecte